SetGlobal("loaded", {
  gzip = true,
  zip = true,
  zipPlugin = true,
  tar = true,
  tarPlugin = true,
  getscript = true,
  getscriptPlugin = true,
  vimball = true,
  vimballPlugin = true,
  ["2html_plugin"] = true,
  matchit = true,
  matchparen = true,
  logiPat = true,
  rrhelper = true,
  netrw = true,
  netrwPlugin = true,
  netrwSettings = true,
})
