gui:
  mouseEvents: false
  skipStashWarning: true
  showRandomTip: false
  showBottomLine: false
  showCommandLog: false
  showIcons: true
git:
  overrideGpg: true
os:
  openCommand: 'nvim --server $NVIM --remote {{filename}}'
